bug:
- all:
    - base-branch: ['3.1.4-experimental-*']
    - head-branch: ['^[\D\d]+\/bug\/[\D\d]+']

enhancement:
- all:
    - base-branch: ['3.1.4-experimental-*']
    - head-branch: ['^[\D\d]+\/enhancement\/[\D\d]+']

documentation:
- any:
    - changed-files: ['README.md']
